### ISSUE TITLE
TypeError on selecting an item

### ISSUE THREAD

**Issue by RonenOfir** [cgberlin/vue-input-dropdown#1]
Hi, when I select item from the dropdown, I get an error.

<img width="382" alt="error" src="https://user-images.githubusercontent.com/30022610/57054786-687af800-6c9f-11e9-8696-209b1029c6c3.png">

**Comment by cgberlin** [comment]
Can you post your template/component where you are using the dropdown? it appears that it isn't recognizing the array of items.

**Comment by RonenOfir** [comment]
You are right, my response from server is not an array. Thanks
